[project]
name = "skibidi"
version = "0.1.0"
description = "The Skibidi card game."
readme = "README.md"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"